[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = { version = "0.15.3", default-features = false, features = ["allocator", "calc-hash", "ckb-types", "libc"] }

[build-dependencies]
cc = "1.0"
